name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and pusht the docker image
      run: |
        docker login --username joseacuna-18 --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build . --tag ghcr.io/joseacuna-18/training-docker-app:latest
        docker push ghcr.io/joseacuna-18/training-docker-app:latest
